name: CI Pipeline

on: 
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.MKDOCS_CI }}
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Mkdocs and dependencies for documentation
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install 'mkdocs >= 1.0.4, < 2' mkdocs-material
    - name: Generate documentation
      run: |
        mkdocs build --clean
        ls
    - name: Saving site as artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: documentation
        path: site
    - name: Install Tox and dependencies for build
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/project.txt
        pip install tox
    - name: Build with tox
      run: |
        tox --notest --sdistonly

        
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.5, 3.6]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/project.txt
        pip install codecov
        pip install tox
    - name: Test with tox
      run: |
        tox -e test
        
  deploy:
    needs: [build_documentation]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dowloading docs stored as artifacts
      uses: actions/download-artifact@v1
      with:
        name: documentation
    - name: Deploy on GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.MKDOCS_CI }}
        BRANCH: gh-pages
        FOLDER: documentation
        
